services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5430:5432'
    volumes:
      - volume-postgres-wb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - service-network

  service:
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - service-network


volumes:
  volume-postgres-wb:
    driver: local

networks:
  service-network:
    driver: bridge